objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>Avg_Cure_Days__c</fullName>
        <label>Avg Cure Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Fatal_Days__c</fullName>
        <label>Avg Fatal Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cure_Date__c</fullName>
        <label>Cure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fatal_Date__c</fullName>
        <label>Fatal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_to_Cure__c</fullName>
        <formula>Cure_Date__c - DateValue(CreatedDate)</formula>
        <label>Number of Days to Cure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_to_Fatal__c</fullName>
        <formula>Fatal_Date__c - DateValue(CreatedDate)</formula>
        <label>Number of Days to Fatal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mild</fullName>
                </value>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Cured</fullName>
                </value>
                <value>
                    <fullName>Fatal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PatientHelper.cls
public class PatientHelper {
   public static  map<id, string> dataChangeFlags(map<id,Patient__c> newRecords, map<id,Patient__c> oldRecords){
        map<id, string> mapdata = new  map<id, string>();
        for(Patient__c pt : newRecords.values()){
            if(pt.Stage__c != oldRecords.get(Pt.Id).Stage__c && pt.Stage__c == 'Cured'){
                //pt.Cure_Date__c = System.today();
                mapdata.put(pt.id, 'Cured');
            }
            if(pt.Stage__c != oldRecords.get(Pt.Id).Stage__c && pt.Stage__c == 'Fatal'){
                //pt.fatal_Date__c = System.today();
                mapdata.put(pt.id, 'Fatal');
            }
        }
        return mapdata;
   }

   public static void AvgCalculate(set<Id> changeStatusIds){
        list<AggregateResult> aggs = [SELECT Area__c, Stage__c, AVG(Number_of_Days_to_Cure__c) avgCured, AVG(Number_of_Days_to_Fatal__c) avgFatal FROM Patient__c WHERE Area__c IN :changeStatusIds GROUP BY Area__c, Stage__c];
        map<Id, Area__c> mapAreas = new map<Id, Area__c>();
        for(AggregateResult agg : aggs ){
            Id areaId = (Id) agg.get('Area__c');
            Area__c area = new Area__c(Id = areaId);
            if(mapAreas != NULL && mapAreas.get(areaId) != NULL){
                area = mapAreas.get(areaId);
            }
            if((string)agg.get('Stage__c') == 'Cured'){
                area.Avg_Cure_Days__c = (double)agg.get('avgCured');
            }
            if((string)agg.get('Stage__c') == 'Fatal'){
                area.Avg_Fatal_Days__c = (double)agg.get('avgFatal');
            }
            mapAreas.put(areaId, area);
        }
        update mapAreas.values();
   }
}